### ISSUE TITLE
/money mysql error

### ISSUE THREAD

**Issue by Trsak** [niccholaspage/Fe#27] opened 2013-08-04 10:43 UTC
When i type /money, it generate this error:
11:26:21 [INFO] Trsak issued server command: /money
11:26:21 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Commu
nications link failure
The last packet successfully received from the server was 272,046 milliseconds a
go.  The last packet sent successfully to the server was 0 milliseconds ago.
11:26:21 [SEVERE]       at sun.reflect.GeneratedConstructorAccessor93.newInstanc
e(Unknown Source)
11:26:21 [SEVERE]       at sun.reflect.DelegatingConstructorAccessorImpl.newInst
ance(DelegatingConstructorAccessorImpl.java:45)
11:26:21 [SEVERE]       at java.lang.reflect.Constructor.newInstance(Constructor
.java:526)
11:26:21 [SEVERE]       at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
11:26:21 [SEVERE]       at com.mysql.jdbc.SQLError.createCommunicationsException
(SQLError.java:1116)
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.jav
a:3082)
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.jav
a:2968)
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:
3516)
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:21
40)
11:26:21 [SEVERE]       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.
java:2626)
11:26:21 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeInternal(Prep
aredStatement.java:2111)
11:26:21 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeQuery(Prepare
dStatement.java:2273)
11:26:21 [SEVERE]       at org.melonbrew.fe.database.databases.SQLDB.loadAccount
Money(SQLDB.java:129)
11:26:21 [SEVERE]       at org.melonbrew.fe.database.Database.getAccount(Databas
e.java:44)
11:26:21 [SEVERE]       at org.melonbrew.fe.API.getAccount(API.java:71)
11:26:21 [SEVERE]       at org.melonbrew.fe.command.commands.BalanceCommand.onCo
mmand(BalanceCommand.java:34)
11:26:21 [SEVERE]       at org.melonbrew.fe.FeCommand.onCommand(FeCommand.java:1
25)
11:26:21 [SEVERE]       at org.melonbrew.fe.FeCommand.sendDefaultCommand(FeComma
nd.java:81)
11:26:21 [SEVERE]       at org.melonbrew.fe.FeCommand.onCommand(FeCommand.java:8
6)
11:26:21 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
11:26:21 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:189)
11:26:21 [SEVERE]       at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCo
mmand(CraftServer.java:523)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.PlayerConnection.handleC
ommand(PlayerConnection.java:962)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.PlayerConnection.chat(Pl
ayerConnection.java:880)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.PlayerConnection.a(Playe
rConnection.java:837)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.Packet3Chat.handle(Sourc
eFile:49)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.NetworkManager.b(Network
Manager.java:296)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.PlayerConnection.e(Playe
rConnection.java:116)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.ServerConnection.b(Sourc
eFile:37)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.DedicatedServerConnectio
n.b(SourceFile:30)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.t(Minecr
aftServer.java:590)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.DedicatedServer.t(Dedica
tedServer.java:226)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.s(Minecr
aftServer.java:486)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.run(Mine
craftServer.java:419)
11:26:21 [SEVERE]       at net.minecraft.server.v1_6_R2.ThreadServerApplication.
run(SourceFile:582)
11:26:21 [SEVERE] Caused by: java.io.EOFException: Can not read response from se
rver. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly
lost.
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
11:26:21 [SEVERE]       at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.jav
a:2979)
11:26:21 [SEVERE]       ... 30 more

How to fix this?

**Comment by Puremin0rez** [comment] 2013-09-06 04:45
Duplicate of this issue:
https://github.com/niccholaspage/Fe/issues/13

@niccholaspage Can you please reinvestigate this problem? It's really annoying and ruins a good Economy plugin.

**Comment by niccholaspage** [comment] 2013-12-30 00:11
Duplicate #13, which I hopefully have fixed.

**Closed as completed by niccholaspage** 2013-12-30 00:11 UTC
