### ISSUE TITLE
Have an account by default

### ISSUE THREAD

**Issue by rcl2748** [niccholaspage/Fe#41] opened 2014-03-23 17:03 UTC
Hello, is there a way to have an account by default, so when a person joins, it will automatically create him an account, and won't require for someone to do /fe create <playername>?

**Comment by niccholaspage** [comment] 2014-04-30 22:43
This is intended behavior but was broken in the recent development builds. Its been fixed by commit 0a5fc4eaab187923011c86c3de1046bd09e4b405.

**Closed as completed by niccholaspage** 2014-04-30 22:43 UTC
